# Generated by Django 4.0.4 on 2022-05-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_last_name_remove_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_code',
        ),
    ]
